services:
  server:
    build: ./server
    container_name: go_app
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: host=db user=$POSTGRES_USER password=$POSTGRES_PASSWORD dbname=$POSTGRES_DB port=$DB_PORT sslmode=disable
      PORT: $API_PORT
      REDIS_PASSWORD: $REDIS_PASSWORD
      REDIS_PORT: $REDIS_PORT
      REDIS_TTL: $REDIS_TTL
      CLIENT_URL: $CLIENT_URL
      CLEINT_DEV_URL: $CLEINT_DEV_URL
    ports:
      - "$API_PORT:$API_PORT"

  # client:
  #   build: ./client
  #   container_name: vue-client
  #   environment:
  #     API_PROXY_PATH: http://go_app:$API_PORT/
  #     NGINX_PORT: $NGINX_PORT
  #   depends_on:
  #     - server
  #   ports:
  #     - "$NGINX_PORT:$NGINX_PORT"

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
      PGDATA: /data
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - ./pg/data:/data
    ports:
      - "$DB_PORT:$DB_PORT"

  redis:
    image: redis:7.4-alpine
    container_name: redis-container
    command: redis-server --requirepass $REDIS_PASSWORD
    volumes:
      - ./redis_data:/data
    ports:
      - "$REDIS_PORT:$REDIS_PORT"

